from vertexai.generative_models import GenerativeModel, Part, SafetySetting
from src.step_5_prompt import prompt

# --- Define Safety Settings ---
safety_settings = [
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=SafetySetting.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE
    ),
]
# --- Define Model Configuration ---
GENERATION_CONFIG = {
    "max_output_tokens": 8192,
    "temperature": 0,
    "top_p": 1,
    "response_mime_type": "application/json",
    "response_schema": {
        "type": "OBJECT",
        "properties": {
            "Explanation": {"type": "STRING"},
            "Summary": {"type": "STRING"},
            "Follow_up": {"type": "STRING"},
            "table_data": {"type": "STRING"},
            "Confidence_Reasoning": {
                "type": "STRING", 
                "description": "Critical analysis of how much of the answer is actually found in the provided snippets."
            },
            "Confidence_Score": {
                "type": "NUMBER", 
                "description": "Based the answer generated by the llm model give the confidence score that how much you are confident about the answer generated by the llm model. value should be between 0 to 1 in decimal value but never keep it 0 or 1."
            },
        },
        "required": ["Explanation", "Summary", "Follow_up", "table_data", "Confidence_Reasoning", "Confidence_Score"],
    },
    "thinking_config": {"thinking_budget": 0},
}

GENERATION_CONFIG1 = {
    "max_output_tokens": 8192,
    "temperature": 0,
    "top_p": 1,
    "response_mime_type": "application/json",
    "response_schema": {
        "type": "OBJECT",
        "properties": {
            "Confidence_Reasoning": {
                "type": "STRING"
            },
            "Confidence_Score": {
                "type": "NUMBER"
            }
        },
        "required": ["Confidence_Reasoning", "Confidence_Score"],
    },
    "thinking_config": {"thinking_budget": 0},
}




# "Confidence_Reasoning": {
#                 "type": "STRING", 
#                 "description": "Critical analysis of how much of the answer is actually found in the provided snippets."
#             },
#             "Confidence_Score": {
#                 "type": "INTEGER", 
#                 "description": "Based the answer generated by the llm model give the confidence score that how much you are confident about the answer generated by the llm model. value should be between 0 to 1 in decimal value."
#             },


